version: "3"
services:

  docker-demo:
    image: i_demo
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure